### ISSUE TITLE
Speed up model initialization

### ISSUE THREAD

**Issue by bwgref** [achronal/nuskybgd-py#4]
Should use the "setPars" formalism rather than changing each parameter when adding the default models with their preset parameters.

When you do it one-by-one, then Xspec evaluates the model every time you change a parameter, which takes forever.

Most important is the internal background with all of the lines.

**Comment by achronal** [comment]
Implemented by https://github.com/achronal/nuskybgd-py/compare/705a1e0a2a30fcefd366f530b527ca6a58076900...master
